import { useMemo, useState } from 'react';
import { Home, Compass, Plus, MessageCircle, Bell, UserRound, Search, ChevronDown, Heart, MessageSquare, Send, Bookmark, MoreHorizontal, Image, CalendarDays, Smile, Sparkles, ArrowUpRight, UsersRound, Clock3, MapPin, Menu, X, Sun, Moon, SlidersHorizontal, Check, Hash, Settings, ShieldAlert, LogOut } from 'lucide-react';
import type { Person, Post } from './types';

const people:Person[]=[
 {id:'p1',name:'Ananya Roy',dept:'Computer Science',semester:'3rd semester',avatar:'photo-1534528741775-53994a69daeb',interests:['AI/ML','Photography','Hackathons'],mutual:'4 shared interests'},
 {id:'p2',name:'Arjun Sen',dept:'Electronics',semester:'5th semester',avatar:'photo-1500648767791-00dcc994a43e',interests:['Robotics','Music','Tech clubs'],mutual:'2 mutual connections'},
 {id:'p3',name:'Ishita Paul',dept:'Computer Science',semester:'3rd semester',avatar:'photo-1531123897727-8f129e1688ce',interests:['Coding','Reading','Workshops'],mutual:'Same department'},
 {id:'p4',name:'Ritwik Dey',dept:'Mechanical',semester:'5th semester',avatar:'photo-1506794778202-cad84cf45f1d',interests:['Football','Photography','Festivals'],mutual:'3 shared interests'}
];
const posts:Post[]=[
 {id:1,person:{...people[0],name:'Rahul Das',dept:'Computer Science',semester:'3rd semester',avatar:'photo-1506794778202-cad84cf45f1d'},time:'2 hours ago',text:'Still thinking about today’s workshop on building things that matter. Big thanks to the Coding Club crew for making it happen! 💡',image:'photo-1516321318423-f06f85e504b3',likes:128,comments:24,tag:'Campus life'},
 {id:2,person:{...people[2],name:'Moumita Saha',avatar:'photo-1534528741775-53994a69daeb'},time:'4 hours ago',text:'A little quiet corner of campus after the rain 🌿 Sometimes the best study break is just looking up from your notes.',image:'photo-1470252649378-9c29740c9fa8',likes:86,comments:12,tag:'Moments'},
 {id:3,person:people[1],time:'Yesterday',text:'Our robotics team is looking for two more people for the inter-college build challenge. If you love tinkering, come say hi at the club room this Thursday! 🤖',likes:42,comments:9,tag:'Clubs'}
];
const events=[{title:'Build Night: Prototyping Lab',date:'OCT 04',time:'4:30 PM',place:'Innovation Hub',type:'Workshop',color:'mint'},{title:'Campus Monsoon Cup',date:'OCT 06',time:'9:00 AM',place:'Sports Ground',type:'Sports',color:'peach'}];
const clubs=[{name:'CGEC Coding Club',members:'248 members',emoji:'</>',tone:'lavender'},{name:'Robotics Society',members:'126 members',emoji:'⚙',tone:'yellow'},{name:'Frame by Frame',members:'89 members',emoji:'◉',tone:'pink'}];
const avatar=(id:string):string=>`https://images.unsplash.com/${id}?auto=format&fit=crop&w=160&h=160&q=80`;
const photo=(id:string):string=>`https://images.unsplash.com/${id}?auto=format&fit=crop&w=1100&q=85`;

export default function App(){
 const [page,setPage]=useState('Home'); const [liked,setLiked]=useState<number[]>([]); const [saved,setSaved]=useState<number[]>([]); const [following,setFollowing]=useState<string[]>([]); const [query,setQuery]=useState(''); const [composer,setComposer]=useState(false); const [draft,setDraft]=useState(''); const [allPosts,setAllPosts]=useState(posts); const [notice,setNotice]=useState(''); const [dark,setDark]=useState(false); const [mobileMenu,setMobileMenu]=useState(false); const [tab,setTab]=useState('For you'); const [notifOpen,setNotifOpen]=useState(false);
 const nav=[{name:'Home',icon:Home},{name:'Discover',icon:Compass},{name:'Messages',icon:MessageCircle},{name:'Notifications',icon:Bell},{name:'Profile',icon:UserRound}];
 const notify=(s:string)=>{setNotice(s);window.setTimeout(()=>setNotice(''),2400)};
 const toggle=<T,>(arr:T[],v:T,set:(x:T[])=>void)=>set(arr.includes(v)?arr.filter(x=>x!==v):[...arr,v]);
 const filtered=useMemo(()=>allPosts.filter(p=>(p.text+p.person.name+p.person.dept+p.tag).toLowerCase().includes(query.toLowerCase())),[allPosts,query]);
 const createPost=()=>{if(!draft.trim())return;setAllPosts([{id:Date.now(),person:{id:'me',name:'You',dept:'Computer Science',semester:'3rd semester',avatar:'photo-1534528741775-53994a69daeb',interests:[]},time:'Just now',text:draft.trim(),likes:0,comments:0,tag:'Campus life'},...allPosts]);setDraft('');setComposer(false);notify('Your post is live ✨')};
 const go=(n:string)=>{setPage(n);setMobileMenu(false);if(n==='Notifications')setNotifOpen(x=>!x)};
 return <div className={dark?'app dark':'app'}>
  <header className="topbar"><button className="mobile-menu icon-button" onClick={()=>setMobileMenu(!mobileMenu)} aria-label="Open menu">{mobileMenu?<X/>:<Menu/>}</button><div className="brand" onClick={()=>go('Home')}><div className="brand-mark">c</div><div className="brand-copy">CGEC<span>CONNECT</span></div></div><div className="top-search"><Search size={18}/><input aria-label="Search students, posts, clubs" value={query} onChange={e=>{setQuery(e.target.value);if(e.target.value)setPage('Search')}} placeholder="Search people, posts, clubs..."/><kbd>⌘ K</kbd></div><div className="top-actions"><button className="icon-button theme-toggle" onClick={()=>setDark(!dark)} aria-label="Toggle theme">{dark?<Sun size={18}/>:<Moon size={18}/>}</button><button className="icon-button notification-top" onClick={()=>{setNotifOpen(!notifOpen);setPage('Notifications')}} aria-label="Notifications"><Bell size={19}/><i/></button><button className="my-avatar" aria-label="Your profile" onClick={()=>go('Profile')}><img src={avatar('photo-1534528741775-53994a69daeb')}/></button></div></header>
  <div className="app-grid">
   <aside className={`left-rail ${mobileMenu?'open':''}`}><div className="rail-section"><p className="rail-label">MENU</p>{nav.map(({name,icon:Icon})=><button key={name} className={`nav-link ${page===name?'active':''}`} onClick={()=>go(name)}><Icon size={19}/><span>{name}</span>{name==='Notifications'&&<b className="nav-count">3</b>}</button>)}<button className="nav-link create-nav" onClick={()=>setComposer(true)}><Plus size={19}/><span>Create post</span></button></div><div className="rail-divider"/><div className="rail-section"><div className="rail-heading"><p className="rail-label">YOUR SPACES</p><button onClick={()=>notify('Spaces coming soon')} aria-label="Add space">+</button></div>{clubs.slice(0,3).map(c=><button className="space-link" key={c.name} onClick={()=>go('Clubs')}><span className={`club-mini ${c.tone}`}>{c.emoji}</span>{c.name.replace('CGEC ','')}</button>)}</div><div className="rail-bottom"><button className="nav-link" onClick={()=>go('Settings')}><Settings size={18}/><span>Settings & privacy</span></button><div className="signed-in"><img src={avatar('photo-1534528741775-53994a69daeb')}/><div><b>Priya Sharma</b><small>CSE · 3rd sem</small></div><ChevronDown size={16}/></div><div className="footnote">Made for our campus <span>✳</span><br/>© 2025 CGEC Connect</div></div></aside>
  <main className="main-content">{page==='Home'?<><div className="welcome-row"><div><p className="eyebrow">WEDNESDAY, SEPTEMBER 23, 2026</p><h1>Your campus, <em>closer.</em></h1><p className="welcome-sub">A little something happening around you.</p></div><button className="new-post-button" onClick={()=>setComposer(true)}><Plus size={17}/> New post</button></div><div className="story-strip"><div className="story your-story" onClick={()=>notify('Story composer coming soon')}><div className="story-ring add-story"><img src={avatar('photo-1534528741775-53994a69daeb')}/><b>+</b></div><span>Your story</span></div>{people.slice(0,3).map((p,i)=><button className="story" key={p.id} onClick={()=>notify(`${p.name}'s story`)}><div className={`story-ring s${i}`}><img src={avatar(p.avatar)}/></div><span>{p.name.split(' ')[0]}</span></button>)}</div><div className="feed-tabs"><button className={tab==='For you'?'selected':''} onClick={()=>setTab('For you')}>For you</button><button className={tab==='Following'?'selected':''} onClick={()=>setTab('Following')}>Following</button><span className="feed-filter"><SlidersHorizontal size={15}/> Latest</span></div><div className="feed-list">{filtered.map(p=><article className="post-card" key={p.id}><div className="post-head"><img className="post-avatar" src={avatar(p.person.avatar)}/><div className="post-user"><b>{p.person.name}<span className="verified">✓</span></b><small>{p.person.dept} <i>·</i> {p.person.semester}</small></div><span className="post-time">{p.time}</span><button className="icon-button more" onClick={()=>notify('Post options')} aria-label="Post options"><MoreHorizontal size={20}/></button></div><p className="post-text">{p.text}</p>{p.image&&<img className="post-image" src={photo(p.image)} alt="Campus post"/>}<div className="post-actions"><button className={liked.includes(p.id)?'liked':''} onClick={()=>toggle(liked,p.id,setLiked)}><Heart size={19} fill={liked.includes(p.id)?'currentColor':'none'}/><span>{p.likes+(liked.includes(p.id)?1:0)}</span></button><button onClick={()=>notify('Comments are ready to explore')}><MessageSquare size={18}/><span>{p.comments}</span></button><button onClick={()=>notify('Link copied to clipboard')}><Send size={18}/></button><button className={`save-action ${saved.includes(p.id)?'saved':''}`} onClick={()=>toggle(saved,p.id,setSaved)} aria-label="Save post"><Bookmark size={18} fill={saved.includes(p.id)?'currentColor':'none'}/></button></div><div className="post-caption"><span className="post-tag">#{p.tag}</span><span>Liked by <b>{p.likes>100?'Ananya and 127 others':'Ishita and '+(p.likes-1)+' others'}</b></span></div></article>)}</div><button className="load-more" onClick={()=>notify('You’re all caught up!')}>You’re all caught up <span>✦</span></button></>:<PageView page={page} query={query} notify={notify} following={following} setFollowing={setFollowing} go={go} />}</main>
   <aside className="right-rail"><section className="profile-card"><div className="profile-card-top"><img src={avatar('photo-1534528741775-53994a69daeb')}/><div><b>Priya Sharma</b><small>Computer Science · 3rd sem</small></div><button className="icon-button" onClick={()=>go('Profile')}><ArrowUpRight size={16}/></button></div><div className="profile-stats"><div><b>12</b><span>posts</span></div><div><b>248</b><span>followers</span></div><div><b>186</b><span>following</span></div></div><div className="profile-progress"><div><span>Profile strength</span><b>80%</b></div><div className="progress-track"><i/></div></div></section><section className="side-section"><div className="side-title"><div><span className="section-icon amber"><Sparkles size={15}/></span><h3>People to know</h3></div><button onClick={()=>go('Discover')}>See all</button></div><div className="suggestion-list">{people.slice(0,3).map(p=><div className="suggestion" key={p.id}><img src={avatar(p.avatar)}/><div className="suggestion-info"><b>{p.name}</b><small>{p.mutual}</small></div><button className={following.includes(p.id)?'follow-btn following':'follow-btn'} onClick={()=>{toggle(following,p.id,setFollowing);notify(following.includes(p.id)?`Unfollowed ${p.name}`:`Following ${p.name}`)}}>{following.includes(p.id)?<Check size={15}/>:<Plus size={15}/>}</button></div>)}</div></section><section className="side-section events-section"><div className="side-title"><div><span className="section-icon coral"><CalendarDays size={15}/></span><h3>Coming up</h3></div><button onClick={()=>go('Events')}>All events</button></div>{events.map(e=><div className="event-row" key={e.title}><div className={`event-date ${e.color}`}><b>{e.date.split(' ')[1]}</b><span>{e.date.split(' ')[0]}</span></div><div className="event-info"><b>{e.title}</b><small><Clock3 size={12}/> {e.time} <i>·</i> <MapPin size={12}/> {e.place}</small></div></div>)}</section><section className="side-section clubs-section"><div className="side-title"><div><span className="section-icon violet"><UsersRound size={15}/></span><h3>Campus clubs</h3></div><button onClick={()=>go('Clubs')}>Explore</button></div>{clubs.map(c=><div className="club-row" key={c.name}><div className={`club-logo ${c.tone}`}>{c.emoji}</div><div><b>{c.name}</b><small>{c.members}</small></div><button onClick={()=>notify(`Opened ${c.name}`)} aria-label={`Open ${c.name}`}><ArrowUpRight size={15}/></button></div>)}</section><div className="right-footer">About · Community guidelines · Privacy<br/>Help center · Terms<br/><span>CGEC CONNECT © 2025</span></div></aside>
  </div>
  <nav className="bottom-nav">{[{name:'Home',icon:Home},{name:'Discover',icon:Compass},{name:'Create',icon:Plus},{name:'Messages',icon:MessageCircle},{name:'Profile',icon:UserRound}].map(({name,icon:Icon})=><button className={page===name?'active':''} key={name} onClick={()=>name==='Create'?setComposer(true):go(name)} aria-label={name}><Icon size={21}/>{name==='Create'&&<span className="bottom-create"/>}</button>)}</nav>
  {composer&&<div className="modal-backdrop" onClick={()=>setComposer(false)}><div className="composer-modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><div><span className="eyebrow">SHARE WITH YOUR CAMPUS</span><h2>Create a post</h2></div><button className="icon-button" onClick={()=>setComposer(false)} aria-label="Close"><X/></button></div><div className="composer-user"><img src={avatar('photo-1534528741775-53994a69daeb')}/><div><b>Priya Sharma</b><small>Sharing with everyone</small></div><ChevronDown size={15}/></div><textarea autoFocus value={draft} onChange={e=>setDraft(e.target.value)} placeholder="What’s happening on campus?"/><div className="composer-tools"><button onClick={()=>notify('Image uploads connect when storage is configured')}><Image size={17}/> Photo</button><button onClick={()=>notify('Add an event from the Events page')}><CalendarDays size={17}/> Event</button><button onClick={()=>notify('Activity tags coming soon')}><Smile size={17}/> Activity</button><span className="composer-tools-spacer"/><button aria-label="Add a hashtag" onClick={()=>setDraft(draft+' #')}><Hash size={17}/></button></div><button className="publish-button" disabled={!draft.trim()} onClick={createPost}>Publish post <ArrowUpRight size={16}/></button></div></div>}
  {notifOpen&&<div className="notification-pop"><div className="notif-header"><b>Notifications</b><button onClick={()=>setNotifOpen(false)}><X size={16}/></button></div><div className="notif-item"><span className="notif-dot pink-dot"><Heart size={14}/></span><p><b>Ananya</b> liked your post <small>12 min ago</small></p></div><div className="notif-item"><span className="notif-dot green-dot"><UserRound size={14}/></span><p><b>Ritwik</b> started following you <small>1 hour ago</small></p></div><div className="notif-item"><span className="notif-dot blue-dot"><MessageCircle size={14}/></span><p><b>Ishita</b> commented on your post <small>3 hours ago</small></p></div><button className="all-notifications" onClick={()=>{go('Notifications');setNotifOpen(false)}}>See all notifications</button></div>}
  {notice&&<div className="toast"><Check size={16}/>{notice}</div>}
 </div>
}

function PageView({page,query,notify,following,setFollowing,go}:{page:string;query:string;notify:(x:string)=>void;following:string[];setFollowing:(x:string[])=>void;go:(x:string)=>void}){
 const [filter,setFilter]=useState('All'); const [peopleTab,setPeopleTab]=useState('Students');
 const follow=(p:Person)=>{setFollowing(following.includes(p.id)?following.filter(x=>x!==p.id):[...following,p.id]);notify(following.includes(p.id)?`Unfollowed ${p.name}`:`Following ${p.name}`)};
 if(page==='Discover'||page==='Search')return <><div className="page-heading"><p className="eyebrow">FIND YOUR PEOPLE</p><h1>{page==='Search'?'Search campus':'Discover'}</h1><p className="welcome-sub">Find your people through shared interests, ideas and campus life.</p></div>{page==='Search'&&<div className="search-mobile"><Search size={18}/><input value={query} placeholder="Search students, posts, clubs..." readOnly/></div>}<div className="discover-controls"><div className="segmented">{['Students','Clubs','Events','Posts'].map(x=><button onClick={()=>setPeopleTab(x)} className={peopleTab===x?'active':''} key={x}>{x}</button>)}</div><button className="filter-button" onClick={()=>setFilter(filter==='All'?'Computer Science':'All')}><SlidersHorizontal size={15}/>{filter==='All'?'Filters':filter}<ChevronDown size={14}/></button></div>{peopleTab==='Students'?<><div className="section-heading-row"><div><h2>People you may want to connect with</h2><p>Picked from shared academic and campus interests.</p></div><span className="results-count">{people.length} students</span></div><div className="people-grid">{people.filter(p=>filter==='All'||p.dept===filter).map(p=><article className="person-card" key={p.id}><div className="person-banner"><span className="person-dept">{p.dept}</span><button className="icon-button" onClick={()=>notify('Profile options')}><MoreHorizontal size={18}/></button></div><img className="person-avatar" src={avatar(p.avatar)}/><div className="person-body"><h3>{p.name}</h3><p>{p.semester} <i>·</i> CGEC</p><div className="shared-reason"><Sparkles size={13}/>{p.mutual}</div><div className="interest-tags">{p.interests.slice(0,2).map(x=><span key={x}>{x}</span>)}</div><div className="person-actions"><button className={following.includes(p.id)?'following-wide':'primary-wide'} onClick={()=>follow(p)}>{following.includes(p.id)?<><Check size={15}/> Following</>:<><Plus size={15}/> Follow</>}</button><button className="message-person" onClick={()=>go('Messages')}><MessageCircle size={17}/></button></div></div></article>)}</div></>:<EmptyDiscovery section={peopleTab} go={go}/>}<button className="load-more" onClick={()=>notify('You’ve seen all suggested connections')}>More connections will appear as the community grows <span>✦</span></button></>;
 if(page==='Profile')return <ProfilePage notify={notify}/>;
 if(page==='Messages')return <MessagesPage notify={notify}/>;
 if(page==='Events')return <EventsPage notify={notify}/>;
 if(page==='Clubs')return <ClubsPage notify={notify}/>;
 if(page==='Notifications')return <NotificationsPage/>;
 if(page==='Settings')return <SettingsPage notify={notify}/>;
 if(page==='Admin')return <AdminPage notify={notify}/>;
 return <div className="page-heading"><p className="eyebrow">CGEC CONNECT</p><h1>{page}</h1><p className="welcome-sub">Your campus community is growing every day.</p><EmptyDiscovery section={page} go={go}/></div>
}

function EmptyDiscovery({section,go}:{section:string;go:(x:string)=>void}){return <div className="empty-discovery"><div className="empty-icon"><Sparkles size={22}/></div><h3>{section==='Posts'?'Campus posts are on the home feed':section==='Clubs'?'Find your campus communities':'Coming into focus'}</h3><p>Explore real people, campus activities, and shared interests from across CGEC.</p><button onClick={()=>go(section==='Clubs'?'Clubs':'Home')}>Explore campus <ArrowUpRight size={15}/></button></div>}

function ProfilePage({notify}:{notify:(x:string)=>void}){const [editing,setEditing]=useState(false);return <><div className="profile-cover"><span>YOUR CORNER OF CAMPUS</span><button onClick={()=>setEditing(!editing)}><Settings size={15}/>{editing?'Done editing':'Edit profile'}</button></div><div className="profile-main"><img className="large-avatar" src={avatar('photo-1534528741775-53994a69daeb')}/><div className="profile-title"><div><h1>Priya Sharma</h1><p>Computer Science <i>·</i> 3rd semester <i>·</i> CGEC</p></div><button className="profile-share" onClick={()=>notify('Profile link copied')}><Send size={16}/></button></div><p className="bio">Curious mind, learning to build thoughtful things. Usually found with a book, a camera or too much coffee. ☕</p><div className="interest-tags profile-tags">{['Programming','Photography','AI/ML','Reading','Hackathons'].map(t=><span key={t}>{t}</span>)}</div><div className="profile-stats wide-stats"><div><b>12</b><span>posts</span></div><div><b>248</b><span>followers</span></div><div><b>186</b><span>following</span></div></div><div className="profile-content-tabs"><button className="active">Posts</button><button>Saved</button><button>About</button></div><div className="profile-post-grid">{posts.slice(0,3).map(p=><div key={p.id} className="profile-tile">{p.image&&<img src={photo(p.image)}/>}<span><Heart size={16} fill="white"/> {p.likes}</span></div>)}</div></div>{editing&&<div className="edit-panel"><div className="modal-head"><h2>Edit your profile</h2><button className="icon-button" onClick={()=>setEditing(false)}><X/></button></div><label>Display name<input defaultValue="Priya Sharma"/></label><label>Short bio<textarea defaultValue="Curious mind, learning to build thoughtful things."/></label><label>Department<select defaultValue="Computer Science"><option>Computer Science</option><option>Electronics</option><option>Mechanical</option></select></label><button className="publish-button" onClick={()=>{setEditing(false);notify('Profile updated')}}>Save changes</button></div>}</>}

function MessagesPage({notify}:{notify:(x:string)=>void}){const [active,setActive]=useState('Ananya Roy');const [message,setMessage]=useState('');const [sent,setSent]=useState<string[]>([]);return <><div className="page-heading"><p className="eyebrow">YOUR CONVERSATIONS</p><h1>Messages</h1><p className="welcome-sub">Good ideas start with a conversation.</p></div><div className="messages-layout"><div className="conversation-list"><div className="conversation-search"><Search size={16}/><input placeholder="Search messages"/></div>{people.slice(0,3).map((p,i)=><button key={p.id} className={`conversation ${active===p.name?'active':''}`} onClick={()=>setActive(p.name)}><div className="online-wrap"><img src={avatar(p.avatar)}/>{i===0&&<i/>}</div><div><b>{p.name}</b><small>{['Hey! Are you coming to the build night?','Sent you the workshop notes 📎','That sounds like a plan!'][i]}</small></div><span>{['10:42','Yesterday','Mon'][i]}</span></button>)}</div><div className="chat-window"><div className="chat-head"><img src={avatar(people.find(p=>p.name===active)?.avatar||people[0].avatar)}/><div><b>{active}</b><small><i/> Active now</small></div><button className="icon-button" onClick={()=>notify('Conversation options')}><MoreHorizontal/></button></div><div className="chat-body"><div className="day-divider"><span>TODAY</span></div><div className="message-bubble theirs">Hey! Are you coming to the build night this Friday?<small>10:41 AM</small></div><div className="message-bubble mine">Definitely! I’ve been wanting to check out the new lab. ✨<small>10:42 AM <Check size={12}/></small></div><div className="typing-line"><span><i/><i/><i/></span> Ananya is typing</div>{sent.map((s,i)=><div className="message-bubble mine" key={i}>{s}<small>Just now <Check size={12}/></small></div>)}</div><form className="chat-compose" onSubmit={e=>{e.preventDefault();if(message.trim()){setSent([...sent,message]);setMessage('')}}}><button type="button" className="icon-button" onClick={()=>notify('Attach a photo')}><Plus/></button><input value={message} onChange={e=>setMessage(e.target.value)} placeholder="Write a message..."/><button type="button" className="icon-button" onClick={()=>notify('Emoji picker')}><Smile size={19}/></button><button className="send-button" aria-label="Send message"><Send size={17}/></button></form></div></div><p className="privacy-note"><ShieldAlert size={14}/> Messages are private. You can block or report someone from conversation options.</p></>}

function EventsPage({notify}:{notify:(x:string)=>void}){const [interested,setInterested]=useState<string[]>([]);return <><div className="page-heading"><p className="eyebrow">MAKE SOMETHING HAPPEN</p><h1>Campus events</h1><p className="welcome-sub">Good things happen when we show up.</p></div><div className="event-feature"><img src={photo('photo-1516321318423-f06f85e504b3')}/><div className="event-feature-overlay"><span>THIS WEEK · WORKSHOP</span><h2>Build Night: Prototyping Lab</h2><p>Bring an idea, meet your people, and make your first prototype.</p><div><CalendarDays size={15}/> Oct 04 · 4:30 PM <i>·</i> <MapPin size={15}/> Innovation Hub</div><button onClick={()=>notify('Event details opened')}>Explore event <ArrowUpRight size={15}/></button></div></div><div className="event-list-heading"><h2>Coming up</h2><div className="segmented"><button className="active">All events</button><button onClick={()=>notify('Showing workshops')}>Workshops</button><button onClick={()=>notify('Showing clubs')}>Clubs</button></div></div><div className="events-grid">{[...events,{title:'Film Photography Walk',date:'OCT 09',time:'3:00 PM',place:'Main Gate',type:'Club activity',color:'lavender'},{title:'Open Mic Evening',date:'OCT 12',time:'5:00 PM',place:'Auditorium',type:'Cultural',color:'pink'}].map((e,i)=><article className="event-card" key={e.title}><div className={`event-card-image event-img-${i}`}><span>{e.type}</span><button onClick={()=>notify('Event link copied')}><ArrowUpRight size={16}/></button></div><div className="event-card-body"><div className={`event-date ${e.color}`}><b>{e.date.split(' ')[1]}</b><span>{e.date.split(' ')[0]}</span></div><div className="event-info"><h3>{e.title}</h3><small><Clock3 size={12}/> {e.time} <i>·</i> <MapPin size={12}/> {e.place}</small><span className="organizer">Organized by CGEC {i%2?'Cultural Society':'Coding Club'}</span></div></div><button className={interested.includes(e.title)?'interested-btn':'interested-btn plain'} onClick={()=>{setInterested(interested.includes(e.title)?interested.filter(x=>x!==e.title):[...interested,e.title]);notify(interested.includes(e.title)?'Removed from interested':'You’re on the interested list!')}}>{interested.includes(e.title)?<><Check size={14}/> Interested</>:<>I’m interested <ArrowUpRight size={14}/></>}</button></article>)}</div></>}

function ClubsPage({notify}:{notify:(x:string)=>void}){const [joined,setJoined]=useState<string[]>([]);return <><div className="page-heading"><p className="eyebrow">FIND YOUR COMMUNITY</p><h1>Campus clubs</h1><p className="welcome-sub">Find a room for the things you love doing.</p></div><div className="clubs-hero"><div><span>BUILT BY STUDENTS</span><h2>Find your <em>people.</em></h2><p>From late-night coding to match-day cheers, there’s a space here for you.</p></div><div className="club-doodles">{clubs.map(c=><div className={`club-doodle ${c.tone}`} key={c.name}>{c.emoji}</div>)}</div></div><div className="club-filter-row"><div className="segmented">{['All clubs','Academic','Creative','Sports'].map((x,i)=><button className={i===0?'active':''} key={x} onClick={()=>notify(`${x} clubs selected`)}>{x}</button>)}</div><span>18 communities</span></div><div className="club-card-grid">{[...clubs,{name:'Campus Photography Circle',members:'67 members',emoji:'◉',tone:'pink'},{name:'Theatre & Arts Collective',members:'104 members',emoji:'✳',tone:'peach'},{name:'CGEC Football Club',members:'214 members',emoji:'⚽',tone:'mint'}].map((c,i)=><article className="club-card" key={c.name}><div className={`club-card-cover ${c.tone}`}><span className={`club-logo ${c.tone}`}>{c.emoji}</span><button className="icon-button" onClick={()=>notify('Club options')}><MoreHorizontal size={17}/></button></div><div className="club-card-body"><span className="eyebrow">{['ACADEMIC','TECHNOLOGY','CREATIVE','CREATIVE','CULTURAL','SPORTS'][i]}</span><h3>{c.name}</h3><p>{['Learn, build and share your curiosity with fellow students.','Designing, building and exploring the future together.','A welcoming space for ideas and creative work.'][i%3]}</p><div className="club-card-meta"><UsersRound size={14}/>{c.members}<span>·</span>{i%2?'Active this week':'3 upcoming events'}</div><button className={joined.includes(c.name)?'following-wide':'primary-wide'} onClick={()=>{setJoined(joined.includes(c.name)?joined.filter(x=>x!==c.name):[...joined,c.name]);notify(joined.includes(c.name)?`Left ${c.name}`:`Welcome to ${c.name}!`)}}>{joined.includes(c.name)?<><Check size={15}/> Joined</>:<>Explore community <ArrowUpRight size={15}/></>}</button></div></article>)}</div></>}

function NotificationsPage(){const items=[['Today','Ananya Roy','started following you','photo-1531123897727-8f129e1688ce','follow'],['Today','Rahul Das','liked your post','photo-1506794778202-cad84cf45f1d','like'],['Today','Ishita Paul','commented: “This looks like such a good time!”','photo-1534528741775-53994a69daeb','comment'],['Yesterday','CGEC Coding Club','Build Night is coming up this Friday','photo-1516321318423-f06f85e504b3','event'],['Yesterday','Arjun Sen','sent you a message','photo-1500648767791-00dcc994a43e','message']];return <><div className="page-heading"><p className="eyebrow">A LITTLE CAMPUS MOMENT</p><h1>Notifications</h1><p className="welcome-sub">The latest from your people and communities.</p></div><div className="notification-page"><div className="notification-toolbar"><div className="segmented"><button className="active">All</button><button>Unread <i>3</i></button></div><button>Mark all as read</button></div>{['Today','Yesterday'].map(day=><section className="notification-group" key={day}><h3>{day}</h3>{items.filter(x=>x[0]===day).map((x,i)=><article className={`notification-row ${i===0&&day==='Today'?'unread':''}`} key={x[1]}><img src={avatar(x[3])}/><div className={`notification-type ${x[4]}`}>{x[4]==='like'?<Heart size={13} fill="currentColor"/>:x[4]==='follow'?<UserRound size={13}/>:x[4]==='event'?<CalendarDays size={13}/>:<MessageCircle size={13}/>}</div><p><b>{x[1]}</b> {x[2]}<small>{i===0?'18 minutes ago':i===1?'2 hours ago':'5 hours ago'}</small></p>{x[4]==='follow'?<button className="small-follow">Follow back</button>:<div className="notification-thumb"/>}</article>)}</section>)}</div></>}

function SettingsPage({notify}:{notify:(x:string)=>void}){return <><div className="page-heading"><p className="eyebrow">YOUR ACCOUNT, YOUR CHOICES</p><h1>Settings & privacy</h1><p className="welcome-sub">Make your campus experience feel right for you.</p></div><div className="settings-layout"><div className="settings-menu">{['Account','Privacy & safety','Notifications','Appearance'].map((x,i)=><button className={i===1?'active':''} key={x}><span>{[<UserRound size={17}/>,<ShieldAlert size={17}/>,<Bell size={17}/>,<Sun size={17}/>][i]}</span>{x}<ArrowUpRight size={14}/></button>)}<button className="settings-admin" onClick={()=>notify('Admin access is restricted to authorized accounts')}><ShieldAlert size={17}/>Admin dashboard</button></div><div className="settings-panel"><span className="eyebrow">PRIVACY & SAFETY</span><h2>Your boundaries matter.</h2><p>Choose how you show up in the CGEC Connect community.</p>{[['Private profile','Only approved followers can see your posts and activity.'],['Messages from followers only','People you follow can start a conversation.'],['Show my semester','Your semester is visible on your profile.'],['Activity status','Let connections see when you’re active.']].map((s,i)=><div className="setting-toggle" key={s[0]}><div><b>{s[0]}</b><small>{s[1]}</small></div><button onClick={e=>{e.currentTarget.classList.toggle('on');notify(`${s[0]} updated`)}} className={`switch ${i===1||i===2?'on':''}`}><i/></button></div>)}<div className="safety-actions"><button onClick={()=>notify('Manage blocked accounts')}><ShieldAlert size={15}/> Manage blocked accounts</button><button onClick={()=>notify('Account deletion request started')}><LogOut size={15}/> Deactivate or delete account</button></div></div></div></>}

function AdminPage({notify}:{notify:(x:string)=>void}){return <><div className="page-heading"><p className="eyebrow">COMMUNITY CARE</p><h1>Admin dashboard</h1><p className="welcome-sub">A safe, welcoming campus starts with all of us.</p></div><div className="admin-alert"><ShieldAlert size={18}/> Admin access is restricted. Sign in with an authorized administrator account to review community reports.</div><div className="admin-stats">{[['Total students','2,481','+ 8% this month'],['Active this week','1,206','Across CGEC'],['Community posts','4,892','+ 124 this week'],['Open reports','06','Needs review']].map(x=><div className="admin-stat" key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><small>{x[2]}</small></div>)}</div><div className="admin-reports"><div className="side-title"><div><span className="section-icon coral"><ShieldAlert size={15}/></span><h3>Recent reports</h3></div><button onClick={()=>notify('Reports require administrator access')}>View all</button></div><p>Report details are visible to authorized moderators only. Actions are recorded in the moderation audit log.</p></div></>}
